spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daimengying/springcloud-config-repo/
#          username :
#          password :

server:
  port: 2001